title: Fractal
tagline: "Output complex, flexible, AJAX/RESTful data structures"
description: "Fractal provides a presentation and transformation layer for complex data output, the like found in AJAX and RESTful APIs."
google_analytics_tracking_id: UA-46050814-4