title: Fractal
tagline: Output complex, flexible, RESTful data structures.
description: "Fractal is an abstraction for filesystems such as Amazon S3, FTP, SFTP, Dropbox and Rackspace"
google_analytics_tracking_id: UA-46050814-3
menu:
    Getting Started:
        Introduction: '/'
        Simple Example: '/simple-example/'
        Installation: '/installation/'
        Glossary: '/glossary/'
        Resources: '/resources/'
        Transformers: '/transformers/'
    Advanced:
        Pagination: '/pagination/'