title: Fractal
tagline: Output complex, flexible, AJAX/RESTful data structures.
description: "Fractal provides a presentation and transformation layer for complex data output, the like found in AJAX and RESTful APIs."
google_analytics_tracking_id: UA-46050814-4
menu:
    Getting Started:
        Introduction: '/'
        Simple Example: '/simple-example/'
        Installation: '/installation/'
        Glossary: '/glossary/'
    Concepts:
        Resources: '/resources/'
        Transformers: '/transformers/'
        Pagination: '/pagination/'